# Tasks:
# Configure the *.yml to automically build your project for each pull request (use maven).
# Configure the *.yml to execute tests automatically.

name: Java CI
# Run this workflow every time we do a pull request in our repository
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        # Sets up jdk with specified Java version
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        # Runs the Maven package target in non-interactive mode 
        # to ensure that the code builds, tests pass, and a package can be created.
      - name: Build with Maven
        run: mvn -B package --file pom.xml